### ISSUE TITLE
Updated hashes for vcredist_2013_*.exe

### ISSUE THREAD

**Issue by dspruell** [jbremer/vmcloak-deps#7]
Notice updated SHA1 hashes for these files?

$ wget -q http://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x64.exe
$ wget -q http://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x86.exe
$ sha1sum vcredist*
8bf41ba9eef02d30635a10433817dbb6886da5a2  vcredist_x64.exe
df7f0a73bfa077e483e51bfb97f5e2eceedfb6a3  vcredist_x86.exe

```
--- .vmcloak/deps/hashes.txt.bak        2015-03-31 23:58:34.742803852 +0000
+++ .vmcloak/deps/hashes.txt    2015-04-01 04:32:56.267529148 +0000
@@ -16,8 +16,8 @@
 vcredist_2012_x86.exe = 7d6f654c16f9ce534bb2c4b1669d7dc039c433c9
 vcredist_2012_x64.exe = c4ac45564e801e1bfd87936cac8a76c5754cdbd4
 
-vcredist_2013_x86.exe = 18f81495bc5e6b293c69c28b0ac088a96debbab2
-vcredist_2013_x64.exe = bef7e7cc1dcc45c0c11682d59c64843727557179
+vcredist_2013_x86.exe = df7f0a73bfa077e483e51bfb97f5e2eceedfb6a3
+vcredist_2013_x64.exe = 8bf41ba9eef02d30635a10433817dbb6886da5a2
 
 FirefoxSetup3.6.20.exe = 1c66e23d9c65e2c8805da9ae033f254f084b16c7
```

**Comment by jbremer** [comment]
I did not notice this, no. Interesting.. If you can do a pull request with the patch that'd be great, otherwise I'll update the hashes later myself.
